#------------------------------------------------------------------------------
# Author: 
# 	Adrian Murillo
# CruzID: 
# 	amurill9
# ID#: 
# 	1573260
# Institution:
# 	UC Santa Cruz
# Course:
# 	CMPS 101
# File Name:
# 	Makefile
#------------------------------------------------------------------------------
#   Makefile for CMPS 101 Programming Assignment 5
#
##  make                     makes FindComponents
#  make GraphTest         makes GraphTest
#  #  make clean               removes binaries
#  make checkFind           tests FindComponents for memory leaks on in3
#  #  make checkClient         tests GraphTest for memory leaks
#------------------------------------------------------------------------------

BASE_SOURCES   = Graph.c List.c
BASE_OBJECTS   = Graph.o List.o
HEADERS        = Graph.h List.h
COMPILE        = gcc -c -std=c99 -Wall
LINK           = gcc -o
REMOVE         = rm -f
MEMCHECK       = valgrind --leak-check=full

FindComponents : FindComponents.o $(BASE_OBJECTS)
		$(LINK) FindComponents FindComponents.o $(BASE_OBJECTS)

GraphTest : GraphTest.o $(BASE_OBJECTS)
		$(LINK) GraphTest GraphTest.o $(BASE_OBJECTS)

FindComponents.o : FindComponents.c $(HEADERS)
		$(COMPILE) FindComponents.c

GraphTest.o : GraphTest.c $(HEADERS)
		$(COMPILE) GraphTest.c

$(BASE_OBJECTS) : $(BASE_SOURCES) $(HEADERS)
		$(COMPILE) $(BASE_SOURCES)

clean :
		$(REMOVE) FindComponents GraphTest FindComponents.o GraphTest.o $(BASE_OBJECTS)

checkFind : FindComponents
		$(MEMCHECK) ./FindComponents in1 out1

checkClient : GraphTest
		$(MEMCHECK) ./GraphTest
