// Filename: stackrecursion.cpp
//
// The file basically contains two functions that generate all subsequences of an input string. One function is the (standard) recursive method,
// while the other is non-recursive and uses a stack. Both these functions have an identical output, and create a (linked) list of strings as their output.
// 
// The code uses the List data structure used in a number of CSE101 assignments and tests.
// 
// USAGE:  (the executable is generated by a Makefile)
//     ./stackrecursion <INPUT FILE> <OUTPUT FILE>
// 
//     Only the first line of <INPUT FILE> is read, as a string. <OUTPUT FILE> contains all subsequences, each in a separate line.
// 
// 
// C. Seshadhri, Jan 2020

#include <iostream>
#include "list.h"
#include <stack>
#include <stdexcept>
#include <fstream>
#include <array>
#include <vector> 
#include <algorithm>
#include <sstream>
using namespace std;


// This class keeps pairs of string. This is useful for simulating the recursion through as stack.
class Pair
{
    public:
        string in_str;
        string fixed_str;
};

// This function generates all subsequences of the input input_str, and outputs them as a list. This function does not use recursion.
// Input: string input_str
// Output: list of all subsequences of input_str
// 
List allSubSeqStack(string input_str)
{
    List final_output; // generate empty list
    stack<class Pair> recurStack; // empty stack that performs the recursion
    Pair init, stacktop; // create a pair to push, to start the stac
    init.in_str = input_str; // put the initial string
    init.fixed_str = ""; // this is the fixed string, initially empty
    recurStack.push(init); // push this pair onto the top

    while(!recurStack.empty()) // while the stack is non-empty
    {
        stacktop = recurStack.top();// get the top pair in stack 
        recurStack.pop(); // remove the top element of stack
        if (stacktop.in_str.length() == 0) // input string is empty, so this is base case
        {
            final_output.insert(stacktop.fixed_str); // insert the fixed string onto list
            continue; // pop the next element of stack
        }
        char last = stacktop.in_str.back(); // get last element of in_str
        stacktop.in_str.pop_back(); // remove last element of stack
        Pair to_push; // setting up elements to push onto stack
        to_push.in_str = stacktop.in_str;
        to_push.fixed_str = stacktop.fixed_str; 
        recurStack.push(to_push); // this is for one recursive call
        to_push.fixed_str = last + stacktop.fixed_str; // this is for next recursive call
        recurStack.push(to_push);
    }
    return final_output;
}
List language(string input_str,int k){
    List final_output;
    stack<class Pair> pairs; 
    Pair prev;
    char c;
    prev.in_str = input_str;
    prev.fixed_str = ""; 
    pairs.push(prev); 
    string buffer = "";
    while(!pairs.empty()) 
    {
        prev=pairs.top();
        pairs.pop();
        if(buffer.size()>0) buffer.pop_back();
        if(prev.in_str==""){
            continue;
        } else{
           c = prev.in_str.back();
           prev.in_str.pop_back();
           prev.fixed_str.push_back(c);
           pairs.push(prev);
           buffer.push_back(c);
           final_output.insert(buffer);
           if((int)pairs.size()==k) continue;
           else{
               Pair curr;
               curr.in_str = input_str;
               curr.fixed_str = "";
               pairs.push(curr);
               buffer.push_back('%');
           }
        }
    }
    return final_output;
}

// This recursive function generates all subsequences of the input in_str *appended* to the fixed_str, and outputs them in the list provided as an argument
// Input: string fixed_str, string in_str, pointer to list list_ptr
// Output: void, but list referenced by list_ptr is modified
// 
void allSubSeqRec(string in_str, string fixed_str, List *list_ptr)
{
    if (in_str.length() == 0) // base case
    {
        list_ptr->insert(fixed_str); // insert the fixed string into list
        return;
    }
    char top = in_str.back(); // get the last element of the string
    in_str.pop_back(); // delete last element of in_str
    allSubSeqRec(in_str, fixed_str, list_ptr); // recursive call for subsequences without top
    allSubSeqRec(in_str, top+fixed_str, list_ptr); //  recursive call for subsequences with top
    return;
}

// This function generates all subsequences of the input in_str, and outputs them as a list. This is the recursive version
// Input: string in_str
// Output: list of all subsequences of in_str
// 
List allSubSeq(string in_str)
{
    List *final_output = new List(); // generate empty list
    allSubSeqRec(in_str,"",final_output); // populate list with output
    return *final_output;
}

List permutations(string input_str){
    List final_output;
    string buffer = "";
    char c;
    stack<Pair> pairs;
    Pair prev;
    prev.in_str=input_str;
    prev.fixed_str="";
    pairs.push(prev);
    while(!pairs.empty()){
        prev=pairs.top();
        pairs.pop();
        if(buffer.size()>0) buffer.pop_back();
        if(prev.in_str==""){
            continue;
        } else{
            c = prev.in_str.back();
            prev.in_str.pop_back();
            Pair curr;
            curr.in_str=prev.in_str+prev.fixed_str;
            curr.fixed_str="";
            prev.fixed_str = c + prev.fixed_str;
            pairs.push(prev);
            buffer.push_back(c);
            if(curr.in_str==""){
                final_output.insert(buffer);
            } else{
                pairs.push(curr);
                buffer.push_back(c);
            }
        }
    }
    return final_output;
}

void recursion(string buffer,string input, List* list, int k){
    char last = input.back();
    input.pop_back();
    for(int i =1;i<=k;i++){
        for(int j=1;j<=i;j++) buffer.push_back(last);
        if(input==""){
            list->insert(buffer);
        }
        else recursion(buffer,input,list,k);
        for(int j=1;j<=i;j++) buffer.pop_back();
    }
}

List rec_stretch(string input, int k){
    List list;
    string buffer ="";
    recursion(buffer,input,&list,k);
    return list;
}

List stretch(string input, int k){
    List list;
    string in = "";
    while(input.size()>0){
        in.push_back(input.back());
        input.pop_back();
    }
    string buffer="";
    char c;
    int count;
    stack<int> counts;
    stack<char> chars;
    chars.push(6);
    counts.push(0);
    while(!chars.empty()){
        count = counts.top();
        c = chars.top();
        counts.pop();
        chars.pop();
        if(count==0){
            c=in.back();
            in.pop_back();
        }
        if(count==k){
            in.push_back(c);
            while(buffer.back()==c) buffer.pop_back();
            continue;
        }
        buffer.push_back(c);
        count++;
        counts.push(count);
        chars.push(c);
        if(in.size()==0) list.insert(buffer);
        else{
            counts.push(0);
            chars.push(c);
        }
    }
    return list;
}

int main(int argc, char** argv)
{
    if (argc < 3) // must provide two arguments as input
    {
        throw std::invalid_argument("Usage: ./hello <INPUT FILE> <OUTPUT FILE>"); // throw error
    }

    ifstream input; // stream for input file
    ofstream output; // stream for output file

    input.open(argv[1]); // open input file
    output.open(argv[2]); // open output file

    string in_str; // to store the input string from the file


    getline(input, in_str); // get the single string from the input file
    
    List myList = stretch(in_str,2); // initializing the linked list

    myList.sort(); // sort the list
    
    output << myList.print("\n") << endl;  // print the list, using a new line as delimiter between items of the list
    
    myList.deleteList(); // free all the memory of this list

    input.close();
    output.close();
}
